In [2]:
import pandas as pd

#### data

In [3]:
original_data = pd.read_parquet("escooter_copy.parquet")

In [4]:
df_org_data = original_data.copy()

In [5]:
# Transformed dtypes of Dataframe   
df_org_data.holiday = df_org_data.holiday.astype(bool)
df_org_data.workingday = df_org_data.workingday.astype(bool)
df_org_data.loc[df_org_data.temp >45, "temp"] = df_org_data.temp.div(100)

In [6]:
dfh = df_org_data.copy()

In [7]:
#Max and Min of Humidity are extreme ?
dfh.humidity.describe().round(2)

count    3755415.00
mean          57.22
std           18.40
min            0.00
25%           43.00
50%           56.00
75%           71.00
max          100.00
Name: humidity, dtype: float64

In [8]:
# no NaN values
dfh.loc[dfh.humidity.isna() ==  True]

Empty DataFrame
Columns: [datetime, holiday, workingday, weather, temp, atemp, humidity, windspeed, registered_customer]
Index: []

#### humidity 100

In [9]:
dfh1 = dfh.loc[dfh.humidity == 100]
dfh1[["datetime", "temp", "atemp", "weather", "windspeed"]].to_clipboard()

In [30]:
dfh2 = dfh1.groupby(["weather", "datetime"]).agg(temp =("temp", "mean"), windspeed= ("windspeed", "mean"), humidity= ("humidity", "mean")).reset_index()
dfh2

,weather,datetime,temp,windspeed,humidity
0,"clear, few clouds",2020-02-08 21:00:28,10.66,12.998,100.0
1,"clear, few clouds",2020-02-08 21:01:47,10.66,12.998,100.0
2,"clear, few clouds",2020-02-08 21:02:14,10.66,12.998,100.0
3,"clear, few clouds",2020-02-08 21:03:10,10.66,12.998,100.0
4,"clear, few clouds",2020-02-08 21:03:24,10.66,12.998,100.0
...,...,...,...,...,...
19528,light snow or rain or thunderstorm,2022-01-01 13:59:25,8.20,0.000,100.0
19529,light snow or rain or thunderstorm,2022-01-01 13:59:28,8.20,0.000,100.0
19530,light snow or rain or thunderstorm,2022-01-01 13:59:59,8.20,0.000,100.0
19531,light snow or rain or thunderstorm,2022-01-01 14:00:17,8.20,0.000,100.0
19532,light snow or rain or thunderstorm,2022-01-01 14:00:21,8.20,0.000,100.0

In [32]:
dfh3 = dfh2.loc[dfh2.weather == "clear, few clouds"].reset_index(drop = True)

In [37]:
dfh3.sort_values(by= "temp", ascending= False)

               weather            datetime   temp  windspeed  humidity
424  clear, few clouds 2020-09-25 18:11:59  24.60      0.000     100.0
503  clear, few clouds 2020-09-25 18:40:14  24.60      0.000     100.0
505  clear, few clouds 2020-09-25 18:40:26  24.60      0.000     100.0
506  clear, few clouds 2020-09-25 18:40:42  24.60      0.000     100.0
507  clear, few clouds 2020-09-25 18:41:21  24.60      0.000     100.0
..                 ...                 ...    ...        ...       ...
37   clear, few clouds 2020-02-08 21:35:36  10.66     12.998     100.0
36   clear, few clouds 2020-02-08 21:35:35  10.66     12.998     100.0
35   clear, few clouds 2020-02-08 21:35:33  10.66     12.998     100.0
34   clear, few clouds 2020-02-08 21:34:58  10.66     12.998     100.0
0    clear, few clouds 2020-02-08 21:00:28  10.66     12.998     100.0

[848 rows x 5 columns]

#### humidity 0

In [14]:
dfh4 = dfh2.loc[dfh2.humidity == 0]

In [15]:
dfh_0 = dfh.loc[dfh.humidity == 0]

In [39]:
dfh01 = dfh_0.groupby(["weather", "datetime"]).agg(temp =("temp", "mean"), windspeed= ("windspeed", "mean"), humidity= ("humidity", "mean")).reset_index()
dfh01

,weather,datetime,temp,windspeed,humidity
0,"cloudy, mist",2020-03-12 17:01:00,18.04,26.0027,0.0
1,"cloudy, mist",2020-03-12 17:02:38,18.04,26.0027,0.0
2,"cloudy, mist",2020-03-12 17:02:52,18.04,26.0027,0.0
3,"cloudy, mist",2020-03-12 17:03:00,18.04,26.0027,0.0
4,"cloudy, mist",2020-03-12 17:03:55,18.04,26.0027,0.0
...,...,...,...,...,...
615,light snow or rain or thunderstorm,2020-03-12 23:54:20,13.94,6.0032,0.0
616,light snow or rain or thunderstorm,2020-03-12 23:54:25,13.94,6.0032,0.0
617,light snow or rain or thunderstorm,2020-03-12 23:55:02,13.94,6.0032,0.0
618,light snow or rain or thunderstorm,2020-03-12 23:55:12,13.94,6.0032,0.0
619,light snow or rain or thunderstorm,2020-03-12 23:59:02,13.94,6.0032,0.0

In [56]:
dfh01.loc[dfh.weather == "cloudy, mist"]

,weather,datetime,temp,windspeed,humidity
102,"cloudy, mist",2020-03-12 17:52:27,18.04,26.0027,0.0
306,light snow or rain or thunderstorm,2020-03-12 12:07:40,17.22,15.0013,0.0
307,light snow or rain or thunderstorm,2020-03-12 12:08:21,17.22,15.0013,0.0
308,light snow or rain or thunderstorm,2020-03-12 12:10:08,17.22,15.0013,0.0
309,light snow or rain or thunderstorm,2020-03-12 12:10:48,17.22,15.0013,0.0
...,...,...,...,...,...
615,light snow or rain or thunderstorm,2020-03-12 23:54:20,13.94,6.0032,0.0
616,light snow or rain or thunderstorm,2020-03-12 23:54:25,13.94,6.0032,0.0
617,light snow or rain or thunderstorm,2020-03-12 23:55:02,13.94,6.0032,0.0
618,light snow or rain or thunderstorm,2020-03-12 23:55:12,13.94,6.0032,0.0
619,light snow or rain or thunderstorm,2020-03-12 23:59:02,13.94,6.0032,0.0

In [38]:
dfh02 = dfh_0.groupby("weather").agg(temp =("temp", "mean"), windspeed= ("windspeed", "mean"), humidity= ("humidity", "mean"))
dfh02

                                         temp  windspeed  humidity
weather
cloudy, mist                        17.078621  22.015414       0.0
light snow or rain or thunderstorm  16.490921  20.078232       0.0

In [18]:
dfh_clip = dfh01.reset_index()
dfh_clip[["weather", "datetime","temp", "humidity"]].to_clipboard()

#### data cleaning

In [27]:
dfh.drop(dfh.loc[(dfh.weather == "clear, few clouds") & (dfh.humidity == 100)].index, inplace= True)

In [28]:
dfh.drop(dfh.loc[(dfh.weather == "light snow or rain or thunderstorm") & (dfh.humidity == 0)].index, inplace= True)

In [50]:
dfh.humidity.quantile(0.001)

22.0

In [54]:
dfh.humidity.quantile(0.999)

94.0

In [29]:
dfh = dfh.loc[dfh.humidity.between(dfh.humidity.quantile(0.001), dfh.humidity.quantile(0.999))]