In [6]:
import pandas as pd

In [7]:
original_data = pd.read_parquet("escooter_copy.parquet")

In [8]:
df_org_data = original_data.copy()

In [9]:
# Transformed dtypes of Dataframe   
df_org_data.holiday = df_org_data.holiday.astype(bool)
df_org_data.workingday = df_org_data.workingday.astype(bool)
df_org_data.loc[df_org_data.temp >45, "temp"] = df_org_data.temp.div(100)

In [10]:
dfh = df_org_data.copy()

In [11]:
# Max and Min of Humidity are extreme ?
dfh.humidity.describe().round(2)

count    3755415.00
mean          57.22
std           18.40
min            0.00
25%           43.00
50%           56.00
75%           71.00
max          100.00
Name: humidity, dtype: float64

In [12]:
# no NaN values
dfh.loc[dfh.humidity.isna() ==  True]

Empty DataFrame
Columns: [datetime, holiday, workingday, weather, temp, atemp, humidity, windspeed, registered_customer]
Index: []

In [13]:
dfh1 = dfh.loc[dfh.humidity == 100]
dfh1[["datetime", "temp", "atemp", "weather", "windspeed"]].to_clipboard()

In [14]:
dfh2 = dfh1.groupby(["weather", "datetime"]).agg(temp =("temp", "mean"), atemp= ("atemp", "mean"), windspeed= ("windspeed", "mean"), humidity= ("humidity", "mean")).reset_index()
dfh2

,weather,datetime,temp,atemp,windspeed,humidity
0,"clear, few clouds",2020-02-08 21:00:28,10.66,12.88,12.998,100.0
1,"clear, few clouds",2020-02-08 21:01:47,10.66,12.88,12.998,100.0
2,"clear, few clouds",2020-02-08 21:02:14,10.66,12.88,12.998,100.0
3,"clear, few clouds",2020-02-08 21:03:10,10.66,12.88,12.998,100.0
4,"clear, few clouds",2020-02-08 21:03:24,10.66,12.88,12.998,100.0
...,...,...,...,...,...,...
19528,light snow or rain or thunderstorm,2022-01-01 13:59:25,8.20,12.12,0.000,100.0
19529,light snow or rain or thunderstorm,2022-01-01 13:59:28,8.20,12.12,0.000,100.0
19530,light snow or rain or thunderstorm,2022-01-01 13:59:59,8.20,12.12,0.000,100.0
19531,light snow or rain or thunderstorm,2022-01-01 14:00:17,8.20,12.12,0.000,100.0
19532,light snow or rain or thunderstorm,2022-01-01 14:00:21,8.20,12.12,0.000,100.0

In [15]:
dfh3 = dfh2.loc[dfh2.weather == "clear, few clouds"].reset_index(drop = True)

In [16]:
dfh3.loc[dfh3.datetime.between("2020-12-1", "2020-12-31")].head(5)

               weather            datetime   temp  atemp  windspeed  humidity
807  clear, few clouds 2020-12-09 00:02:06  18.04  21.97     12.998     100.0
808  clear, few clouds 2020-12-09 00:02:55  18.04  21.97     12.998     100.0
809  clear, few clouds 2020-12-09 00:04:53  18.04  21.97     12.998     100.0
810  clear, few clouds 2020-12-09 00:05:07  18.04  21.97     12.998     100.0
811  clear, few clouds 2020-12-09 00:06:10  18.04  21.97     12.998     100.0

In [17]:
dfh3.to_clipboard()

In [18]:
dfh4 = dfh2.loc[dfh2.humidity == 0]

In [19]:
dfh_0 = dfh.loc[dfh.humidity == 0]

In [20]:
dfh01 = dfh_0.groupby(["weather", "datetime"]).agg(temp =("temp", "mean"), atemp= ("atemp", "mean"), windspeed= ("windspeed", "mean"), humidity= ("humidity", "mean"))
dfh01

                                                         temp   atemp  \
weather                            datetime
cloudy, mist                       2020-03-12 17:01:00  18.04  21.970
                                   2020-03-12 17:02:38  18.04  21.970
                                   2020-03-12 17:02:52  18.04  21.970
                                   2020-03-12 17:03:00  18.04  21.970
                                   2020-03-12 17:03:55  18.04  21.970
...                                                       ...     ...
light snow or rain or thunderstorm 2020-03-12 23:54:20  13.94  17.425
                                   2020-03-12 23:54:25  13.94  17.425
                                   2020-03-12 23:55:02  13.94  17.425
                                   2020-03-12 23:55:12  13.94  17.425
                                   2020-03-12 23:59:02  13.94  17.425

                                                        windspeed  humidity
weather                            datetime
cloudy, mist                       2020-03-12 17:01:00    26.0027       0.0
                                   2020-03-12 17:02:38    26.0027       0.0
                                   2020-03-12 17:02:52    26.0027       0.0
                                   2020-03-12 17:03:00    26.0027       0.0
                                   2020-03-12 17:03:55    26.0027       0.0
...                                                           ...       ...
light snow or rain or thunderstorm 2020-03-12 23:54:20     6.0032       0.0
                                   2020-03-12 23:54:25     6.0032       0.0
                                   2020-03-12 23:55:02     6.0032       0.0
                                   2020-03-12 23:55:12     6.0032       0.0
                                   2020-03-12 23:59:02     6.0032       0.0

[620 rows x 4 columns]

In [21]:
dfh02 = dfh_0.groupby("weather").agg(temp =("temp", "mean"), atemp= ("atemp", "mean"), windspeed= ("windspeed", "mean"), humidity= ("humidity", "mean"))
dfh02

                                         temp      atemp  windspeed  humidity
weather
cloudy, mist                        17.078621  20.726069  22.015414       0.0
light snow or rain or thunderstorm  16.490921  20.130680  20.078232       0.0